version: '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=hmv